// Compares the CLI with the operation inventory, schemas/operations-v0.json (#286, slice 286c). The inventory is
// generated by Userland's private repo from its source of truth, and the MCP server builds its tools from the same
// list, so a command or option the CLI gains, loses or renames without the inventory changing is drift: the two
// clients would no longer offer the same operations. `npm run validate:operations` fails on any.
//
// Two checks, one for each direction:
//
// - The help text against the inventory (static). Every command line in `userland --help` (Usage and Aliases) must be
//   an inventory operation's command or alias, with the same number of positional arguments, and every --flag on it
//   must be one of that operation's inputs. Every released operation must be on a Usage line, and every alias on a
//   line of its own. An operation the inventory calls planned that the CLI already has is drift too.
// - The CLI against the inventory (behaviour). The built CLI runs each operation, once with only what it requires and
//   once more with each optional flag (and each flag's alias), against a stand-in API on 127.0.0.1 that records the
//   requests. It must never answer "Unknown option" or print the usage text, and every request it makes must be one
//   of the operation's API calls in the inventory.
import { spawn } from "node:child_process";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import type { AddressInfo } from "node:net";
import { tmpdir } from "node:os";
import path from "node:path";

export interface InventoryInput {
  cli: string;
  source: "argument" | "flag" | "stdin";
  aliases?: string[];
  required: boolean;
  takes_value: boolean;
  repeatable?: boolean;
  role: string;
}

export interface InventoryOperation {
  id: string;
  kind: string;
  cli: { command: string; aliases: string[]; status: "released" | "planned" };
  inputs: InventoryInput[];
  api: Array<{ method: string; path: string }>;
}

export interface UsageLine {
  section: "usage" | "aliases";
  /** The command words after `userland`, such as ["apps", "slugs", "add"]. */
  command: string;
  /** Positional arguments in order, such as ["<app-id>", "[dir]"]. */
  args: string[];
  /** Every --flag on the line. */
  flags: string[];
  text: string;
}

const isWord = (token: string) => /^[a-z][a-z-]*$/u.test(token);

/** The command lines of `userland --help`: everything under "Usage:" and "Aliases:" up to the next blank line. */
export function parseUsage(help: string): UsageLine[] {
  const lines: UsageLine[] = [];
  let section: UsageLine["section"] | null = null;
  for (const raw of help.split("\n")) {
    if (/^Usage:\s*$/u.test(raw)) {
      section = "usage";
      continue;
    }
    if (/^Aliases:\s*$/u.test(raw)) {
      section = "aliases";
      continue;
    }
    if (!raw.trim()) {
      section = null;
      continue;
    }
    if (!section) continue;
    const text = raw.trim().replace(/\s{2,}\(.*\)$/u, "");
    const tokens = text.split(/\s+/u);
    if (tokens[0] !== "userland") continue;
    const words: string[] = [];
    let index = 1;
    while (index < tokens.length && (isWord(tokens[index]) || /^[a-z-]+(\|[a-z-]+)+$/u.test(tokens[index]))) {
      words.push(tokens[index]);
      index += 1;
    }
    if (words.length === 0) continue; // `userland [--help]`, `userland --version`
    const rest = tokens.slice(index).join(" ");
    const flags = [...rest.matchAll(/--[a-z][a-z-]*/gu)].map((match) => match[0]);
    // Positional arguments: <x> or [x] tokens that aren't a flag's value (the token right after a flag).
    const args: string[] = [];
    const restTokens = tokens.slice(index);
    for (let position = 0; position < restTokens.length; position += 1) {
      const token = restTokens[position].replace(/\.\.\.$/u, "");
      const previous = restTokens[position - 1] ?? "";
      const afterFlag = /--[a-z-]+$/u.test(previous.replace(/^\[/u, ""));
      if (/^<[^>]+>$/u.test(token) && !afterFlag) args.push(token);
      else if (/^\[[^\]-][^\]]*\]$/u.test(token) && !token.includes(" ") && !afterFlag) args.push(token);
    }
    // `api-keys list|create|rename|revoke ...` stands for one line per alternative.
    const alternatives = words.map((word) => word.split("|"));
    const expand = (prefix: string[], rest: string[][]): string[][] => (rest.length === 0 ? [prefix] : rest[0].flatMap((word) => expand([...prefix, word], rest.slice(1))));
    for (const command of expand([], alternatives)) {
      lines.push({ section, command: command.join(" "), args: rest.endsWith("...") && alternatives.some((options) => options.length > 1) ? [] : args, flags, text });
    }
  }
  return lines;
}

function flagNames(input: InventoryInput): string[] {
  return [input.cli, ...(input.aliases ?? [])];
}

/** The operation whose command or one of whose aliases is `command`. */
function operationFor(operations: InventoryOperation[], command: string): InventoryOperation | undefined {
  return operations.find((operation) => operation.cli.command === command || operation.cli.aliases.includes(command));
}

/** Drift between the help text and the inventory, as sentences. */
export function staticDrift(operations: InventoryOperation[], usage: UsageLine[]): string[] {
  const problems: string[] = [];
  for (const line of usage) {
    const operation = operationFor(operations, line.command);
    if (!operation) {
      problems.push(`\`userland ${line.command}\` is in the CLI's help, but no inventory operation has it as its command or an alias.`);
      continue;
    }
    const known = new Set(operation.inputs.filter((input) => input.source === "flag").flatMap(flagNames));
    for (const flag of line.flags) {
      if (!known.has(flag)) problems.push(`\`userland ${line.command}\` takes ${flag} in the CLI's help, but ${operation.id} has no such input in the inventory.`);
    }
    const shape = /\.\.\.$/u.test(line.text) && line.args.length === 0;
    const inventoryArgs = operation.inputs.filter((input) => input.source === "argument");
    if (!shape && line.args.length !== inventoryArgs.length) {
      problems.push(
        `\`userland ${line.command}\` takes ${line.args.length} positional argument(s) in the CLI's help (${line.args.join(" ") || "none"}), but ${operation.id} lists ${inventoryArgs.length} (${inventoryArgs.map((input) => input.cli).join(" ") || "none"}).`
      );
    }
  }
  for (const operation of operations) {
    const onUsage = usage.some((line) => line.section === "usage" && line.command === operation.cli.command);
    if (operation.cli.status === "released" && !onUsage) problems.push(`${operation.id} is released in the inventory, but \`userland ${operation.cli.command}\` isn't on a Usage line of the CLI's help.`);
    if (operation.cli.status === "planned" && onUsage) problems.push(`The CLI has \`userland ${operation.cli.command}\`, but the inventory still says ${operation.id} is planned. Mark it released.`);
    if (operation.cli.status !== "released") continue;
    for (const alias of operation.cli.aliases) {
      if (!usage.some((line) => line.command === alias)) problems.push(`${operation.id} has the alias \`userland ${alias}\` in the inventory, but the CLI's help doesn't list it.`);
    }
  }
  return problems;
}

/** A regular expression for an inventory API path: each `:name` is one segment, and a `:…_path` is the rest of the URL. */
export function pathPattern(apiPath: string): RegExp {
  const pattern = apiPath
    .split("/")
    .map((segment) => (segment.startsWith(":") ? (segment.endsWith("_path") ? ".+" : "[^/]+") : segment.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&")))
    .join("/");
  return new RegExp(`^${pattern}$`, "u");
}

export interface Probe {
  /** What was run, for messages: `apps slugs add <app-id> <slug> --account`. */
  label: string;
  argv: string[];
}

/** Example values the probes pass: the CLI checks some of them before it calls the API. */
const SAMPLES: Record<string, string> = {
  "<app-id>": "app_probe",
  "<release-id>": "rel_probe",
  "<NAME>": "PROBE_SECRET",
  "<slug>": "probe-address",
  "<hostname>": "probe.example.com",
  "<api-key-id>": "key_probe",
  "<account-id>": "acct_probe",
  "--account": "acct_probe",
  "--app": "app_probe",
  "--name": "Probe key",
  "--email": "probe@example.com",
  "--role": "member",
  "--expires-in-days": "7",
  "--type": "app.request",
  "--severity": "error",
  "--release": "rel_probe",
  "--version": "rel_probe",
  "--limit": "5",
  "--cursor": "probe-cursor",
  "--range": "7d",
  "--plan": "free",
  "--to": "starter",
  "--subject": "Probe",
  "--message": "Probe",
  "--collection": "probe",
  "--value": "probe-value",
  "--api-key": "ul_probe_key"
};

/** The runs that exercise an operation: its required inputs alone, then each optional flag and flag alias once. */
export function probesFor(operation: InventoryOperation, folders: { app: string; empty: string }, base: string): Probe[] {
  const value = (name: string): string => {
    if (name === "--api-base-url" || name === "--console-url") return base;
    if (name === "<dir>") return folders.app;
    if (/^\[.*\]$/u.test(name)) return folders.empty;
    return SAMPLES[name] ?? "probe";
  };
  const positional = operation.inputs.filter((input) => input.source === "argument").map((input) => value(input.cli));
  // --no-browser is always passed where the operation takes it: a probe must never open a browser on the machine.
  const always = (input: InventoryInput) => input.source === "flag" && (input.required || input.cli === "--no-browser");
  const requiredFlags = operation.inputs.filter(always).flatMap((input) => (input.takes_value ? [input.cli, value(input.cli)] : [input.cli]));
  const commandWords = operation.cli.command.split(" ");
  const baseArgv = [...commandWords, ...positional, ...requiredFlags];
  const probes: Probe[] = [{ label: `${operation.cli.command} (required inputs only)`, argv: baseArgv }];
  for (const input of operation.inputs.filter((candidate) => candidate.source === "flag" && !always(candidate))) {
    for (const name of flagNames(input)) {
      probes.push({ label: `${operation.cli.command} ${name}`, argv: [...baseArgv, ...(input.takes_value ? [name, value(input.cli)] : [name])] });
    }
  }
  for (const alias of operation.cli.aliases) {
    probes.push({ label: `${alias} (alias of ${operation.cli.command})`, argv: [...alias.split(" "), ...positional, ...requiredFlags] });
  }
  return probes;
}

interface Recorded {
  method: string;
  path: string;
}

/** A stand-in API on 127.0.0.1 that records each request and answers an empty JSON object. */
async function standInApi(): Promise<{ base: string; take(): Recorded[]; close(): Promise<void> }> {
  let recorded: Recorded[] = [];
  const server = createServer((request: IncomingMessage, response: ServerResponse) => {
    request.resume();
    request.on("end", () => {
      recorded.push({ method: request.method ?? "GET", path: new URL(request.url ?? "/", "http://127.0.0.1").pathname });
      response.writeHead(200, { "content-type": "application/json" });
      response.end("{}");
    });
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const { port } = server.address() as AddressInfo;
  return {
    base: `http://127.0.0.1:${port}`,
    take: () => {
      const taken = recorded;
      recorded = [];
      return taken;
    },
    close: () => new Promise<void>((resolve) => server.close(() => resolve()))
  };
}

function runCli(cliEntry: string, argv: string[], env: NodeJS.ProcessEnv, timeoutMs = 5_000): Promise<{ output: string; timedOut: boolean }> {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [cliEntry, ...argv], { env, stdio: ["pipe", "pipe", "pipe"] });
    let output = "";
    let timedOut = false;
    child.stdout.on("data", (chunk) => (output += chunk));
    child.stderr.on("data", (chunk) => (output += chunk));
    const timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
    }, timeoutMs);
    child.on("close", () => {
      clearTimeout(timer);
      resolve({ output, timedOut });
    });
    child.stdin.end("probe-value\n");
  });
}

/** The behaviour check: drift found by running the built CLI against the stand-in API. */
export async function behaviourDrift(operations: InventoryOperation[], cliEntry: string): Promise<string[]> {
  const problems: string[] = [];
  const api = await standInApi();
  const scratch = await mkdtemp(path.join(tmpdir(), "userland-operations-"));
  try {
    const app = path.join(scratch, "app");
    await mkdir(path.join(app, "public"), { recursive: true });
    await writeFile(path.join(app, "manifest.userland.json"), JSON.stringify({ app: { name: "Probe" }, runtime: { static_root: "public" }, resources: {} }));
    await writeFile(path.join(app, "public", "index.html"), "<!doctype html><title>Probe</title>");
    for (const operation of operations) {
      const probes = probesFor(operation, { app, empty: path.join(scratch, "empty") }, api.base);
      for (const probe of probes) {
        const home = await mkdtemp(path.join(scratch, "home-"));
        await rm(path.join(scratch, "empty"), { recursive: true, force: true });
        const env: NodeJS.ProcessEnv = {
          PATH: process.env.PATH,
          HOME: home,
          USERLAND_API_BASE_URL: api.base,
          USERLAND_CONSOLE_URL: api.base,
          USERLAND_API_KEY: "ul_probe_key",
          USERLAND_CREDENTIALS_FILE: path.join(home, "credentials.json"),
          NO_COLOR: "1",
          // Belt and braces with --no-browser: nothing the CLI might hand a URL to can open one.
          BROWSER: "true",
          DISPLAY: ""
        };
        const { output } = await runCli(cliEntry, probe.argv, env);
        const requests = api.take();
        if (/Unknown option/u.test(output)) problems.push(`\`userland ${probe.label}\`: the CLI refuses an input the inventory lists for ${operation.id} (${output.match(/Unknown option[^\n]*/u)?.[0]}).`);
        else if (/^Usage:\s*$/mu.test(output) && /userland \[--help\]/u.test(output)) problems.push(`\`userland ${probe.label}\`: the CLI prints its usage text, so it doesn't take ${operation.id}'s inputs as the inventory lists them.`);
        const patterns = operation.api.map((apiCall) => ({ method: apiCall.method, pattern: pathPattern(apiCall.path) }));
        for (const request of requests) {
          if (!patterns.some((candidate) => candidate.method === request.method && candidate.pattern.test(request.path))) {
            problems.push(`\`userland ${probe.label}\` calls ${request.method} ${request.path}, which isn't one of ${operation.id}'s API calls in the inventory.`);
          }
        }
      }
    }
  } finally {
    await api.close();
    await rm(scratch, { recursive: true, force: true });
  }
  return [...new Set(problems)];
}
