// Fails when the CLI drifts from the operation inventory, schemas/operations-v0.json (#286, slice 286c). See
// scripts/cli-operations.ts for the two checks. Runs on the built CLI (npm run cli:build first; npm test does).
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { behaviourDrift, parseUsage, staticDrift, type InventoryOperation } from "./cli-operations.js";

const root = path.resolve(import.meta.dirname, "..");
const cliEntry = path.join(root, "cli", "dist", "index.js");
if (!existsSync(cliEntry)) {
  console.error("cli/dist/index.js is missing. Run npm run cli:build first.");
  process.exit(1);
}

const inventory = JSON.parse(readFileSync(path.join(root, "schemas", "operations-v0.json"), "utf8")) as { operations: InventoryOperation[] };
const help = spawnSync(process.execPath, [cliEntry, "--help"], { encoding: "utf8" });
const usage = parseUsage(`${help.stdout}${help.stderr}`);
if (usage.length < 20) {
  console.error(`Couldn't read the command lines from \`userland --help\` (found ${usage.length}).`);
  process.exit(1);
}

const problems = [...staticDrift(inventory.operations, usage), ...(await behaviourDrift(inventory.operations, cliEntry))];
if (problems.length > 0) {
  console.error(`The CLI and schemas/operations-v0.json disagree (${problems.length}):`);
  for (const problem of problems) console.error(`- ${problem}`);
  console.error(
    "\nThe inventory is generated by Userland's private repo (packages/shared/src/operationInventory.ts, npm run operations:export). Change the inventory there together with the CLI, so the MCP server offers the same operations."
  );
  process.exit(1);
}
console.log(`The CLI matches schemas/operations-v0.json: ${inventory.operations.length} operations, ${usage.length} help lines.`);
